title: 新的开始，充满挑战和乐趣
name: songqing
markdown: kramdown

github: https://github.com/songqing
weibo: http://weibo.com/zsq164

#语法高亮
pygments: true

#首先概要显示分隔符
excerpt_separator: "\n\n\n"

markdown: kramdown

#分页
paginate: 5

#url格式
#permalink: /:year/:month/:day/:title
permalink:  /posts/:title

# comment
comments:
    duoshuo:
        name:  songqing                             # short name
        rcomments:
            num: 10
            avatar: 0
            time: 0
            title: 0
            admin: 0
            length: 26
